// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DigitalRoot(arg1:number):Promise<number>;

export function GetConstants():Promise<Record<string, number>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetThemeForFrequency(arg1:number):Promise<main.Theme>;

export function Greet(arg1:string):Promise<string>;

export function NewQuaternion(arg1:number,arg2:number,arg3:number,arg4:number):Promise<main.Quaternion>;

export function QuaternionDot(arg1:main.Quaternion,arg2:main.Quaternion):Promise<number>;

export function QuaternionMagnitude(arg1:main.Quaternion):Promise<number>;

export function QuaternionMultiply(arg1:main.Quaternion,arg2:main.Quaternion):Promise<main.Quaternion>;

export function QuaternionNormalize(arg1:main.Quaternion):Promise<main.Quaternion>;

export function QuaternionSlerp(arg1:main.Quaternion,arg2:main.Quaternion,arg3:number):Promise<main.Quaternion>;

export function SpawnPhyllotaxis(arg1:number,arg2:number,arg3:number):Promise<Array<main.Particle>>;
