// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DigitalRoot(arg1) {
  return window['go']['main']['App']['DigitalRoot'](arg1);
}

export function GetConstants() {
  return window['go']['main']['App']['GetConstants']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetThemeForFrequency(arg1) {
  return window['go']['main']['App']['GetThemeForFrequency'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NewQuaternion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['NewQuaternion'](arg1, arg2, arg3, arg4);
}

export function QuaternionDot(arg1, arg2) {
  return window['go']['main']['App']['QuaternionDot'](arg1, arg2);
}

export function QuaternionMagnitude(arg1) {
  return window['go']['main']['App']['QuaternionMagnitude'](arg1);
}

export function QuaternionMultiply(arg1, arg2) {
  return window['go']['main']['App']['QuaternionMultiply'](arg1, arg2);
}

export function QuaternionNormalize(arg1) {
  return window['go']['main']['App']['QuaternionNormalize'](arg1);
}

export function QuaternionSlerp(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuaternionSlerp'](arg1, arg2, arg3);
}

export function SpawnPhyllotaxis(arg1, arg2, arg3) {
  return window['go']['main']['App']['SpawnPhyllotaxis'](arg1, arg2, arg3);
}
